language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - coverage run --branch -m doctest docs.rst
  - coverage run --append --branch -m doctest extra.rst
after_success:
  - coveralls
